FROM python:3.12-slim

WORKDIR /app

COPY generator/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/
COPY generator/data_generator.py ./data_generator.py

ENV PYTHONPATH=/app/src

CMD ["python", "data_generator.py"]
