apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: data
spec:
  serviceName: clickhouse-headless
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8
          ports:
            - name: http
              containerPort: 8123
            - name: tcp
              containerPort: 9000
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-auth
                  key: CLICKHOUSE_PASSWORD
          volumeMounts:
            - name: chdata
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d
      # MERGED VOLUMES HERE
      volumes:
        - name: config
          configMap:
            name: clickhouse-config
  volumeClaimTemplates:
    - metadata:
        name: chdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi